server:
  port: 8081
  servlet:
    context-path: /
    session:
      timeout: 60m
  error:
    path: /error
  tomcat:
    uri-encoding: UTF-8



girl:         #自定义属性
  cupSize: F
  age: 18
  height: 160
