spring:
  profiles:
    active: dev   #应用application-dev的配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://104.199.198.38:3306/dbgirl?useUnicode=true&characterEncoding=utf-8&useSSL=false   #连接到linux服务器
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource   #阿里巴巴Driud连接池
  jpa:
    hibernate:
      ddl-auto: create   #建表方式
    show-sql: true   #显示sql语句
  redis:
    database: 1   #索引
    host: 104.199.198.38
    port: 6379
    password:   #默认为空
    jedis:
      pool:
        max-active: 8   #连接池最大连接数
        max-wait: -1ms   #连接池最大阻塞等待时间 (负数为不限制)
        max-idle: 8   #连接池最大空闲连接
        min-idle: 0   #连接池最小空闲连接
    timeout: 5s    #连接超时时间
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false   #关闭缓存，即时刷新，上线生产环境需要改为true

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.demo.domain.entity



